/*DELETE
FROM data_warehouse.CARTEIRA_PAGAMENTOS
WHERE DATA_INT = '2025-12-31 23:00:00.000'*/

CREATE TABLE [data_warehouse].[GESTAO_PAGAMENTOS]
(
    [PAGAMENTO] NVARCHAR (50) NULL,
    [FORMA_PG] NVARCHAR (100) NULL,
    [CPF] NVARCHAR (50) NULL,
    [NOME_PAGADOR] NVARCHAR (800) NULL,
    [MENSALIDADE] FLOAT NULL,
    [VENC_BOLETO] DATETIME NULL,
    [DATA_PAG] DATETIME NULL,
    [COMPETENCIA] VARCHAR (50) NULL,
    [VALOR_BR] FLOAT NULL,
    [VALOR_CPL] FLOAT NULL
);

